service: d3-lambda-map2

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
  plot:
    handler: handler.plot
    events:
      - http:
          path: plot/get
          method: get
          headers:
              Content-Type: text/html

plugins:
  - serverless-offline
